/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package common.lib.v1;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum GeoLocType { 
  GPS, LCC, UTM  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GeoLocType\",\"namespace\":\"common.lib.v1\",\"symbols\":[\"GPS\",\"LCC\",\"UTM\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
